# PyTorch: freeCodeCamp - Full Course
### Section 1: Basics

Classical Programming:<br>
Rules + Data -> Answers

Supervised Machine Learning:<br>
Data + Answers -> Rules

In [3]:
import torch

Create a tensor:

In [4]:
t1 = torch.tensor(4.)
t1

tensor(4.)

Get data type fo the tensor:

In [5]:
t1.dtype

torch.float32

Create a 3D tensor

In [9]:
t2 = torch.tensor([[1., 2, 3, 4], [5., 6, 7, 8], [9., 10, 11, 12]])

Find shape of tensor:

In [10]:
t2.shape

torch.Size([3, 4])

Create input, weight and bias tensors:

In [12]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

We set requires_grad to true to automatically calculate the gradient with respect to those tensors.

Perform arithmetic operations on the tensors:

In [13]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

Calculate the derivative of y with respect to the other tensors:

In [14]:
y.backward()
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


PyTorch works with Numpy, OpenCV and Pandas:

In [16]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

Get torch tensor from numpy array:

In [18]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

This is different from the following, as it creates a copy of the data whereas the previous does not:

In [17]:
y = torch.tensor(x)

We can also convert tensors to ndarrays:

In [19]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])