# PyTorch: freeCodeCamp - Full Course
### Section 2: Linear Regression

Import libraries:

In [16]:
import numpy as np
import torch

Load input data:

In [17]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

Load target data:

In [18]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

Convert to tensors:

In [19]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

Initialize weights and biases (randomly):

In [20]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
w, b

(tensor([[ 0.4010,  0.1256,  0.0588],
         [ 0.8079, -0.9664, -1.0900]], requires_grad=True),
 tensor([-0.5870,  1.5252], requires_grad=True))

Model:

In [21]:
def model(x):
    return x @ w.t() + b

Run model on input data:

In [22]:
preds = model(inputs)
preds

tensor([[  39.6298,  -51.1177],
        [  50.7199,  -79.7602],
        [  54.5418, -120.9046],
        [  47.8917,    2.0437],
        [  43.2551, -111.8046]], grad_fn=<AddBackward0>)

Compare with targets:

In [23]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Calculate MSE between model outputs and targets:

In [24]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

loss = mse(preds, targets)
loss

tensor(17588.3594, grad_fn=<DivBackward0>)

Computer gradient of loss with respect to parameters:

In [25]:
loss.backward()
w.grad, b.grad

(tensor([[ -2207.9634,  -3404.2024,  -1920.9136],
         [-13374.3086, -16341.0742,  -9790.5791]]),
 tensor([ -28.9923, -164.3087]))

Compute a single gradient update:

In [26]:
with torch.no_grad():   # no gradient tracking
    w -= w.grad * 1e-5  # learning rate
    b -= b.grad * 1e-5  # learning rate
    w.grad.zero_()      # zero gradients
    b.grad.zero_()      # zero gradients

Train the model for 1000 epochs:

In [29]:
for _ in range(1000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

Evaluate model:

In [31]:
preds = model(inputs)
loss = mse(preds, targets)
print(w)
print(b)
print(loss)

tensor([[-0.3568,  0.9099,  0.5324],
        [-0.2020,  0.9753,  0.4387]], requires_grad=True)
tensor([-0.5899,  1.5267], requires_grad=True)
tensor(14.0377, grad_fn=<DivBackward0>)
